[cmd_duration]
min_time = 10_00 # Show command duration over 10,000 milliseconds (=10 sec)
format = " took [$duration]($style)"

# [directory]
# truncation_length = 5
# format = "[$path]($style)[$lock_symbol]($lock_style) "

[git_branch]
style = "bold yellow"

[git_commit]
commit_hash_length = 8
style = "bold white"

[git_status]
modified = "* "
style = "bright-white"
format = "$modified"

[hostname]
disabled = true

[time]
time_format = "%T"
format = "$time($style) "
style = "bright-white"
disabled = false

[username]
style_user = "bold dimmed blue"
show_always = false



[directory]
read_only = " "
truncation_length = 10
truncate_to_repo = true # truncates directory to root folder if in github repo
style = "bold italic blue"

[nodejs]
format = "via [node $version](bold green) "
detect_files = ["package.json"]
detect_folders = ["node_modules"]
